version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongo
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # nginx.confをマウント
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
