version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongo

  # nginx:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./src:/var/www/html
  #   depends_on:
  #     - php-fpm

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
